spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      acks: all
#      transaction-id-prefix: order-${random.uuid}
      key-serialize: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      max:
        in:
          flight:
            requests:
              per:
                connection: 1
      transaction:
        timeout:
          ms: 10000
      properties:
        linger:
          ms: 50
        enable:
          idempotence: true
    consumer:
      group-id: order-group-id
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      maxPollRecords: 1
      isolation-level: read_committed
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        max:
          poll:
            interval:
              ms: 15000
order:
  topic: order_topic_poc